version: '3.8'

services:
  mysql_test:
    image: mysql:8.3.0
    container_name: db-container_test
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - mysql_data_test:/var/lib/mysql
    networks:
      - igma-cliente-teste

volumes:
  mysql_data_test:

networks:
  igma-cliente-teste:
    driver: bridge